<a href="https://colab.research.google.com/github/joshimohitm9/Python_imp_Libraries/blob/main/Numpy_part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# creting one dimentionl array
a=np.array([1,2,36,4,5],np.int8)

In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
# dtype of numpy array
a

array([ 1,  2, 36,  4,  5], dtype=int8)

In [5]:
# fetching the value with index number 4
a[4]

5

In [6]:
a[2]

36

In [7]:
# show you the number of rows and columns
a.shape

(5,)

In [8]:
a.size

5

In [9]:
# data type is int
a.dtype

dtype('int8')

In [10]:
# changing the value of array at the index number 2
a[2]=3
a

array([1, 2, 3, 4, 5], dtype=int8)

In [11]:
# creating 2 dimentional array
b=np.array([[1,2,3]])
b

array([[1, 2, 3]])

In [12]:
shape=b.shape
print(" no of Rows",shape[0])
print("no of Coumns",shape[1])

 no of Rows 1
no of Coumns 3


In [13]:
b.dtype

dtype('int64')

In [14]:
# numpy array with 0 row and 1 column
b[0,1]

2

In [15]:
# chnaging the value of numpy array of 0 row and 2 column with 4
b[0,2]=4

In [16]:
b

array([[1, 2, 4]])

In [17]:
# creating matrix
z=np.array([[1,2,3],
           [4,5,6],
           [7,0,1]])
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [18]:
print("Shape of Martix --",z.shape)
z.dtype

Shape of Martix -- (3, 3)


dtype('int64')

In [19]:
# total element
z.size

9

In [20]:
# Transpose the Matrix
z.T

array([[1, 4, 7],
       [2, 5, 0],
       [3, 6, 1]])

In [21]:
x=np.array([[1,6,3],
           [4,5,9],
           [7,9,9]])

In [22]:
# Addition of 2 matix
z+x

array([[ 2,  8,  6],
       [ 8, 10, 15],
       [14,  9, 10]])

In [23]:
# Simple Multipliation of Matrix
z*x

array([[ 1, 12,  9],
       [16, 25, 54],
       [49,  0,  9]])

In [24]:
# matrix multiplication of 2 array
np.matmul(x,z)

array([[ 46,  32,  42],
       [ 87,  33,  51],
       [106,  59,  84]])

In [25]:
# or we can use this also for matrix multiplication
x.dot(z)

array([[ 46,  32,  42],
       [ 87,  33,  51],
       [106,  59,  84]])

In [26]:
# creating a 2d numpy marix with 0 value that contain 3 rows and 3 columns
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
# creating a 2d numpy marix with 1 value that contain 3 rows and 3 columns
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
# creating a array in the ranfe of (1,11) having gap of 2
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [29]:
# linspace is a NumPy function that returns evenly spaced numbers over a specified interval.
#  It takes three arguments: start, stop, and num

a=np.linspace(1,10,20)
a


array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [30]:
# np.empty is a NumPy function that creates an uninitialized array of specified shape and data type
c=np.empty((4,4))
c

array([[ 1.13947652e-313,  0.00000000e+000,  3.00000000e+000,
         1.00000000e+000],
       [ 1.00000000e+000,  1.00000000e+000,  1.00000000e+000,
         3.00000000e+000],
       [-1.00000000e+000,  3.00000000e+000, -1.00000000e+000,
         1.00000000e+000],
       [-3.00000000e+000,  1.00000000e+000, -3.00000000e+000,
         0.00000000e+000]])

In [31]:
c[0,2]=5656657
print("Dtype is ",c.dtype)
c

Dtype is  float64


array([[ 1.13947652e-313,  0.00000000e+000,  5.65665700e+006,
         1.00000000e+000],
       [ 1.00000000e+000,  1.00000000e+000,  1.00000000e+000,
         3.00000000e+000],
       [-1.00000000e+000,  3.00000000e+000, -1.00000000e+000,
         1.00000000e+000],
       [-3.00000000e+000,  1.00000000e+000, -3.00000000e+000,
         0.00000000e+000]])

In [32]:
# crating a array with diagonal value as 1 and other values as 0
np.identity((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
# creeating a array in the range of 0 to 66
k=np.arange(66)
k

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65])

In [34]:
# reshape method in NumPy can be used to change the shape of an array to any desired shape as long as the total number of elements remains the same.
before=k.reshape((3,22))

# ravel is a function in NumPy that returns a flattened 1D array version of the input array.
after =k.ravel()

In [35]:
print("""Before Flattened""",before)

print(90*"-")

print("""After Flattened""",after)


Before Flattened [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43]
 [44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65]]
------------------------------------------------------------------------------------------
After Flattened [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65]


In [36]:
print("""Matirx z :
""",z)
print("""Matirx x :
""",x)

Matirx z :
 [[1 2 3]
 [4 5 6]
 [7 0 1]]
Matirx x :
 [[1 6 3]
 [4 5 9]
 [7 9 9]]


In [37]:
# sum @ axis =0
z.sum(axis=0)

array([12,  7, 10])

In [38]:
x.sum(axis=0)

array([12, 20, 21])

In [39]:
# sum @ axis =1
x.sum(axis=1)

array([10, 18, 25])

In [40]:
z.sum(axis=1)

array([ 6, 15,  8])

In [41]:
np.sqrt(z)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 0.        , 1.        ]])

In [42]:
z.min()

0

In [43]:
z.max()

7

In [44]:
z.T

array([[1, 4, 7],
       [2, 5, 0],
       [3, 6, 1]])

In [45]:
z.sort()
z

array([[1, 2, 3],
       [4, 5, 6],
       [0, 1, 7]])

In [46]:
import  numpy as np


l=[]
m=[]
n=[]
print(" FOR MATRIX 1")
print("-"*10)
for i in range(0,3):
  a=int(input(f"enter for {i} array of first row :"))
  l.append(a)
for j in range(0,3):
  b=int(input(f"enter for {j} array of second row:"))
  m.append(b)
for k in range(0,3):
  c=int(input(f"enter for {k} array of third row:"))
  n.append(c)
r=[l,m,n]
arr=np.array(r)
print(arr)

x=[]
y=[]
z=[]
print(80*"-")
print(" FOR MATRIX 2")
print("-"*10)
for i in range(0,3):
  o=int(input(f"enter  for {i} array first row :"))
  x.append(o)
for j in range(0,3):
  p=int(input(f"enter  for {j} array second row:"))
  y.append(p)
for k in range(0,3):
  q=int(input(f"enter  for {k} array third row::"))
  z.append(q)
s=[x,y,z]
print(50*"-")
mrr=np.array(s)
print(mrr)

print("="*50)
print(f"sum of two array is \n  {arr+mrr}")
print(50*"-")
print(f" Matrix multiplication of two array is \n  {arr.dot(mrr)}")





 FOR MATRIX 1
----------
enter for 0 array of first row :1
enter for 1 array of first row :2
enter for 2 array of first row :3
enter for 0 array of second row:4
enter for 1 array of second row:5
enter for 2 array of second row:6
enter for 0 array of third row:7
enter for 1 array of third row:8
enter for 2 array of third row:9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------------------------------------------
 FOR MATRIX 2
----------
enter  for 0 array first row :9
enter  for 1 array first row :8
enter  for 2 array first row :7
enter  for 0 array second row:6
enter  for 1 array second row:5
enter  for 2 array second row:4
enter  for 0 array third row::3
enter  for 1 array third row::2
enter  for 2 array third row::1
--------------------------------------------------
[[9 8 7]
 [6 5 4]
 [3 2 1]]
sum of two array is 
  [[10 10 10]
 [10 10 10]
 [10 10 10]]
--------------------------------------------------
 Matrix multiplication of two array is 
  [[ 30  24  18]
 [ 

In [47]:
# creating 2 d array using ndmin
a=np.array([1,2,3,4,5],ndmin=2)
print(a)
a.ndim

[[1 2 3 4 5]]


2

In [48]:
a=np.array([[1,2,3],
            [2,3,4],
            [3,4,5]])

In [49]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [50]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [51]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [52]:
a=np.random.rand(4)
a

array([0.11174236, 0.82026014, 0.60117111, 0.80548585])