<a href="https://colab.research.google.com/github/joshimohitm9/Python_imp_Libraries/blob/main/Numpy_part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# importing library
import numpy as np

In [2]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
a.dtype

dtype('int64')

In [4]:
# Numpy with 4d
a=np.array([1,2,3,4],ndmin=4)
a

array([[[[1, 2, 3, 4]]]])

In [5]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# dingonals are 1
a=np.identity((5))
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
# similat to the np.idnetify()
a=np.eye((3))
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# 3d array
a=np.array([[1,2,3,4],
            [2,3,4,5],
            [3,4,5,6]])
a

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [10]:
b=np.arange((23))
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [11]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [12]:
a

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [13]:
# value at (row,columns) = (1,1)
print("Value at row = 1 and column= 1 is : ",a[1,1])

Value at row = 1 and column= 1 is :  3


In [14]:
x=a[2,2]=6
print("the changed value at at row = 2 and column= 2 is :",x)
a

the changed value at at row = 2 and column= 2 is : 6


array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 6, 6]])

In [15]:
a=np.linspace(1,5,6)
a

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [16]:
a=np.empty((3,3))
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
a=np.array([[1,2,3,4,5,6],
            [2,3,4,8,6,7],
            [1,2,3,4,5,6]])
a

array([[1, 2, 3, 4, 5, 6],
       [2, 3, 4, 8, 6, 7],
       [1, 2, 3, 4, 5, 6]])

In [18]:
print("index of maximum value :",a.argmax())
print("index of minimum value :",a.argmin())
print("Maximum Value :",a.min())
print("Minimum Value :",a.max())

index of maximum value : 9
index of minimum value : 0
Maximum Value : 1
Minimum Value : 8


In [19]:
a=np.array([1,2,3,4,5,6,7],ndmin=3)
print("Dimension of the array :",a.ndim)
print("Array is :",a)

Dimension of the array : 3
Array is : [[[1 2 3 4 5 6 7]]]


In [20]:
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
print(a[1:3])

[2 3]


In [22]:
print(a[2:9:2])

[3 5 7 9]


In [23]:
# ndmin used to create the dimention of the array
a=np.array([1,2,3,4],ndmin=2)

# slicing
print(a[0,1:3])

[2 3]


In [24]:
a.shape

(1, 4)

In [25]:
a.size

4

In [26]:
# concate all the values
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 2 3 4 5]


In [27]:
# provide u only unique values
a=np.unique(c)
print(a)

[1 2 3 4 5]
